# Site settings
title: bu he Blog
header-img: img/home-bg.jpg
email: bugu1986@126.com
description: "React Naitve,Micro service,ReactJS"
baseurl: ""
url: "http://blog.qiufit.cn"
twitter_username: qiufit
github_username:  buhe
facebook_username:  buhe

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
