# Site settings
title: Clean Blog
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: "简洁 易用 笔试Online 面试Online!"
baseurl: ""
url: "http://blog.hiredash.cn"
twitter_username: hiredash
github_username:  hiredash
facebook_username:  hiredash

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
